name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        if: contains(github.event.head_commit.message, 'pack')
        runs-on: self-hosted
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: 设置 node 版本
              uses: actions/setup-node@v2.3.0
              with:
                  node-version: 18.17.0

            - name: 安装依赖
              run: sh install.sh

            - name: 构建渲染进程项目
              run: pnpm run make

            - name: 构建项目
              run: echo done!
